version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    ports: 
      - "9200:9200"
    volumes: 
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    ports:
      - "5601:5601"
    volumes:
      - "kibana_data:/usr/share/kibana/data"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    depends_on: 
      - elasticsearch

volumes:  
  elasticsearch_data: 
    driver: local
  kibana_data:
    driver: local